### ISSUE TITLE
Polybar incorrect path to bars.local.txt

### ISSUE THREAD

**Issue by dmtnikolaev** [stnrepin/dotfiles#1]
Got an error while trying to run polybar from script
```sh
ami% ./polybar/.config/polybar/launch.sh
./polybar/.config/polybar/launch.sh: line 16: /home/dmtnik/.config/polybar//bars.local.txt: No such file or directory 
Polybar launched... Ok
```

Maybe problem in line `CUR_CONFIG_DIR=~/.config/polybar`
instead should be  `CUR_CONFIG_DIR=~/polybar/.config/polybar`

P.s: all paths installed with `stow` as designed

**Comment by stnrepin** [comment]
To use `launch.sh` you need a file (`~/.config/polybar/bars.local.txt`) which contains polybar bars you want to use in your setup.

Are you sure you have installed `@desktop1/polybar` with Stow? Something like:

```sh
cd ~
stow @desktop1/polybar
```

This should place `bars.local.txt` in `~/.config/polybar` next to `launch.sh`.

**Comment by dmtnikolaev** [comment]
Oops, i've installed desktop configs with
```
stow @desktop1
```

And this created excessive directories, such as `~/xorg` and `~/polybar`
